image: maven:latest

cache:
  paths:
    - .m2/repository/
    - target/
stages:
  - build
  - test
  - package

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

build:
  stage: build
  script:
    - mvn compile
  only:
    - master

test:
  stage: test
  script:
    - mvn test
  only:
    - master

package:
  stage: package
  script:
    - mvn package
  only:
    - master
  artifacts:
    paths:
      - target/*.jar
