image: maven:latest

cache:
  paths:
    - .m2/repository/
    - target/
stages:
  - build
  - test

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

build:
  stage: build
  script:
    - mvn clean package
  only:
    - master
  artifacts:
    paths:
      - target/*.jar

test:
  stage: test
  script:
    - mvn clean test
  only:
    - master
