image: maven:latest

cache:
  paths:
    - .m2/repository/
    - target/
stages:
  - build

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

build:
  stage: build
  script:
    - sh build.sh
  only:
    - master
  artifacts:
    paths:
      - target/*.jar