version: '2'

networks:
  kolibri-network:
    driver: bridge

services:

  database: # MYSQL Database Server
    container_name: kolibri-database
    restart: always
    image: mysql
    ports:
      - 3306:3306

    networks:
      - kolibri-network

    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: kolibri
      MYSQL_PASSWORD: kolibri
      MYSQL_DATABASE: kolibridb


  api: # Kolibri API
    container_name: kolibri-api
    restart: always
    image: leonlatsch/kolibri-server:1.0.0
    ports:
      - 8080:8080

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config:/config

    networks:
      - kolibri-network

    depends_on:
      - database

  broker: # RabbitMQ Server
    container_name: kolibri-broker
    restart: always
    image: rabbitmq:management
    ports:
      - 15672:15672
      - 5678:5678

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./assets/rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      - ./assets/rabbitmq/enabled_plugins:/etc/rabbitmq/enabled_plugins

    networks:
      - kolibri-network

  proxy: # Traefik Reverse proxy
    container_name: kolibri-proxy
    restart: always
    image: traefik:v2.0
    ports:
      - 80:80
      - 443:443
      - 5672:5672
    networks:
      - kolibri-network

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./assets/traefik/config.yml:/etc/traefik/traefik.yml
      - ./assets/traefik/dynamic-config.yml:/etc/traefik/dynamic-config.yml
      - ./assets/traefik/acme.json:/etc/traefik/acme.json
      - ./assets/traefik/users:/etc/traefik/users
