spring:

  datasource:
    initialization-mode: always
    password: olivia
    url: jdbc:mysql://olivia-database:3306/oliviadb
    username: olivia

  jpa:
    generate-ddl: true
    hibernate:
        ddl-auto: none
    properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL5Dialect

  rabbitmq:
    host: olivia-queue
    password: guest
    username: guest
    port: 5672
