spring:

  datasource:
    initialization-mode: always
    password: kolibri
    url: jdbc:mysql://kolibri-database:3306/kolibridb
    username: kolibri

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    open-in-view: true # default setting to remove warning

  rabbitmq:
    host: kolibri-broker
    password: kolibri
    username: kolibri
    port: 5678
    ext-port: 5672
    http-port: 15672

admin: # default admin:admin
  initial-username: admin
  initial-password: 8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918
