spring:

  datasource:
    initialization-mode: always
    password: olivia
    url: jdbc:mysql://testserver:3306/oliviadb
    username: olivia

  jpa:
    generate-ddl: true
    hibernate:
        ddl-auto: none
    properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL5Dialect
    open-in-view: true # default setting to remove warning

  rabbitmq:
    host: testserver
    password: olivia
    username: olivia
    port: 5672
