spring:

  datasource:
    initialization-mode: always
    password: olivia
    url: jdbc:mysql://olivia-database:3306/oliviadb
    username: olivia

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    open-in-view: true # default setting to remove warning

  rabbitmq:
    host: olivia-queue
    password: olivia
    username: olivia
    port: 5672
    http-port: 15672

admin: # default admin:admin
  initial-username: admin
  initial-password: 8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918
