entryPoints:
  http:
    address: ":80"

  https:
    address: ":443"

  api:
    address: ":8090"

  mq:
    address: ":5672"

api:
  dashboard: true

providers:
  file:
    filename: "/etc/traefik/dynamic-config.yml"
