logLevel = "INFO"
defaultEntryPoints = ["http", "https"] # Add amqp later

[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
  address = ":443"
  [entryPoints.https.tls]
  [entryPoints.api]
  address = ":8090"
# add basic auth

[api]
entrypoint = "api"
dashboard = true

[retry]

[file]
watch = true

[backends]
  [backends.olivia-backend]
    [backends.olivia-backend.servers]
      [backends.olivia-backend.servers.main]
      url = "http://olivia-backend:8080"
      weight = 1
  [backends.olivia-queue]
      [backends.olivia-queue.servers]
        [backends.olivia-queue.servers.main]
        url = "http://olivia-queue:15672"
        weight = 1
  [backends.olivia-proxy]
      [backends.olivia-proxy.servers]
        [backends.olivia-proxy.servers.main]
        url = "http://localhost:8090"
        weight = 1

[frontends]
  [frontends.olivia-backend]
  entryPoints = ["https"]
  backend = "olivia-backend"
  passHostHeader = true
  [frontends.olivia-backend.routes]
    [frontends.olivia-backend.routes.route]
    rule = "PathPrefixStrip:/api;PathPrefix:/api"

  [frontends.olivia-queue]
  entryPoints = ["https"]
  backend = "olivia-queue"
  passHostHeader = true
  [frontends.olivia-queue.routes]
    [frontends.olivia-queue.routes.route]
    rule = "PathPrefixStrip:/queue;PathPrefix:/queue"

  [frontends.olivia-proxy]
  entryPoints = ["https"]
  backend = "olivia-proxy"
  passHostHeader = true
  [frontends.olivia-proxy.routes]
    [frontends.olivia-proxy.routes.route]
    rule = "PathPrefixStrip:/proxy;PathPrefix:/proxy"

[acme]
email = "dev.leonlatsch@gmail.com"
storage = "/etc/traefik/acme/acme.json"
entryPoint = "https"
onHostRule = true
[[acme.domains]]
  main = "olivia.leonlatsch.de"
  sans = ["olivia.leonlatsch.de"]
[acme.httpChallenge]
  entryPoint = "http"
