entryPoints:
  http:
    address: ":80"

  https:
    address: ":443"

  mq:
    address: ":56722"

api:
  dashboard: true

log:
  level: INFO # DEBUG ERROR

#accessLog: {} # debug

providers:
  file:
    watch: true
    filename: /etc/traefik/dynamic-config.yml
