entryPoints:
  http:
    address: ":80"

  https:
    address: ":443"

  mq:
    address: ":5672"

api:
  dashboard: true

log:
  level: INFO

providers:
  file:
    filename: "/etc/traefik/dynamic-config.yml"
