entryPoints:
  http:
    address: ":80"

  https:
    address: ":443"
    tls: {}

  api:
    address: ":8090"

  mq:
    address: ":25672"

api:
  dashboard: true
  entryPoint: api

providers:
  file:
    filename: "/etc/traefik/dynamic-config.yml"
