entryPoints:
  http:
    address: ":80"

  https:
    address: ":443"

log:
  level: INFO # DEBUG ERROR

accessLog: {} # debug

providers:
  file:
    watch: true
    filename: /etc/traefik/dynamic-config.yml

certificatesResolvers:
  acme_default:
    acme:
      email: <email-address>
      storage: /etc/traefik/acme.json
      httpChallenge:
        entryPoint: http