entryPoints:
  http:
    address: ":80"

  https:
    address: ":443"

api:
  dashboard: true

log:
  level: INFO # DEBUG ERROR

#accessLog: {} # debug

providers:
  file:
    watch: true
    filename: /etc/traefik/dynamic-config.yml

certificatesResolvers:
  acme_default:
    acme:
      email: dev.leonlatsch@gmail.com
      storage: /etc/traefik/acme.json
      httpChallenge:
        entryPoint: http