entryPoints:
  http:
    address: ":80"

  https:
    address: ":443"

  mq:
    address: ":56722"

  traefik:
    address: ":8090"

api:
  dashboard: true
  insecure: true

log:
  level: INFO

accessLog: {} # Remove in production

providers:
  file:
    watch: true
    filename: /etc/traefik/dynamic-config.yml
