entryPoints:
  http:
    address: ":80"

  https:
    address: ":443"

  mq:
    address: ":5672"

  traefik:
    address: ":8090"

api:
  dashboard: true
  insecure: true

log:
  level: DEBUG

providers:
  file:
    filename: "/etc/traefik/dynamic-config.yml"
