http:
  routers:
    api-router:
      rule: "Path(`/api`)"
      service: api-service

    mq-dashboard-router:
      rule: "Path(`/mq-dashboard`)"
      service: mq-dashboard-service

    proxy-router:
      rule: "Path(`/proxy`)"
      service: proxy-service
      middlewares:
        - admin-auth

  services:
    api-service:
      loadBalancer:
        servers:
          - url: "http://olivia-backend:8080"

    mq-dashboard-service:
      loadBalancer:
        servers:
          - url: "http://olivia-queue:15672/#/"

    proxy-service:
      loadBalancer:
        servers:
          - url: "http://localhost:8090"

  middlewares:
    admin-auth:
      basicAuth:
        removeHeader: true
        users:
          - "admin:$2y$12$WZPPrMZUgMxIwyesvaLqjuWJ0gztFfqertyz9iVL.I.6qhMPSOLr."

tcp:
  services:
    mq-service:
      loadBalancer:
        servers:
          - url: "tcp://olivia-queue:56722"

  routers:
    mq-router:
      entryPoints:
        - "mq"
      rule: "HostSNI(`*`)"
      service: mq-service
