http:
  routers:
    api-router:
      rule: "PathPrefixStrip(`/api`)"
      service: api-service

    mq-dashboard-router:
      rule: "PathPrefixStrip(`/mq-dashboard`)"
      service: mq-dashboard-service

    proxy-router:
      rule: "PathPrefixStrip(`/proxy`)"
      service: api@internal
      middlewares:
        - auth

  services:
    api-service:
      loadBalancer:
        servers:
          - url: "http://olivia-backend:8080"

    mq-dashboard-service:
      loadBalancer:
        servers:
          - url: "http://olivia-queue:15672/#/"

  middlewares:
    auth:
      basicAuth:
        users:
          - "test:$apr1$H6uskkkW$IgXLP6ewTrSuBkTrqE8wj/"

tcp:
  services:
    mq-service:
      loadBalancer:
        servers:
          - address: "olivia-queue:56722"

  routers:
    mq-router:
      entryPoints:
        - mq
      rule: "HostSNI(`*`)"
      service: mq-service
