http:
  routers:
    backend-router:
      entryPoints:
        - https
        - http
      rule: "PathPrefix(`/`)"
      service: backend-service
      tls:
        certResolver: acme_default
        domains:
          - main: <domain>
      middlewares:
        - strip

    mq-dashboard-router:
      entryPoints:
        - https
        - http
      rule: "PathPrefix(`/mq`)"
      service: mq-dashboard-service
      tls:
        certResolver: acme_default
        domains:
          - main: <domain>
      middlewares:
        - strip

  services:
    backend-service:
      loadBalancer:
        passHostHeader: true
        servers:
          - url: "http://olivia-backend:8080"

    mq-dashboard-service:
      passHostHeader: true
      loadBalancer:
        servers:
          - url: "http://olivia-queue:15672"

  middlewares:

    strip:
      stripPrefix:
        prefixes:
          - "/mq"
