http:
  routers:
    api-router:
      rule: "PathPrefix(`/api`)"
      service: api-service

    mq-dashboard-router:
      rule: "PathPrefix(`/mq-dashboard`)"
      service: mq-dashboard-service

    proxy-router:
      rule: "PathPrefix(`/proxy`)"
      service: proxy-service

  services:
    api-service:
      loadBalancer:
        servers:
          - url: "http://olivia-backend:8080"

    mq-dashboard-service:
      loadBalancer:
        servers:
          - url: "http://olivia-queue:15672/#/"

    proxy-service:
      loadBalancer:
        servers:
          - url: "http://localhost:8090"

  middlewares:
    admin-auth:
      basicAuth:
        usersFile: "/etc/traefik/admins"

tcp:
  services:
    mq-service:
      loadBalancer:
        servers:
          - address: "olivia-queue:56722"

  routers:
    mq-router:
      entryPoints:
        - mq
      rule: "HostSNI(`*`)"
      service: mq-service
