http:
  routers:
    api-router:
      rule: "PathPrefix(`/api`)"
      service: api-service
      middlewares:
        - strip

    mq-dashboard-router:
      rule: "PathPrefix(`/mq`)"
      service: mq-dashboard-service
      middlewares:
        - strip

    proxy-router:
      rule: "PathPrefix(`/proxy`)"
      service: api@internal
      middlewares:
        - auth
        - strip

  services:
    api-service:
      loadBalancer:
        passHostHeader: true
        servers:
          - url: "http://olivia-backend:8080"

    mq-dashboard-service:
      passHostHeader: true
      loadBalancer:
        servers:
          - url: "http://olivia-queue:15672"

  middlewares:
    auth:
      basicAuth:
        users:
          - "test:$apr1$H6uskkkW$IgXLP6ewTrSuBkTrqE8wj/"

    strip:
      stripPrefix:
        prefixes:
          - "/proxy"
          - "/api"
          - "/mq"

tcp:
  services:
    mq-service:
      loadBalancer:
        servers:
          - address: "olivia-queue:56722"

  routers:
    mq-router:
      entryPoints:
        - mq
      rule: "HostSNI(`*`)"
      service: mq-service
