http:
  routers:
    backend-router:
      entryPoints:
        - https
        - http
      rule: "PathPrefix(`/`)"
      service: api-service
      tls:
        certResolver: acme_default
        domains:
          - main: <domain>
      middlewares:
        - strip

    mq-dashboard-router:
      entryPoints:
        - https
        - http
      rule: "PathPrefix(`/mq`)"
      service: mq-dashboard-service
      tls:
        certResolver: acme_default
        domains:
          - main: <domain>
      middlewares:
        - strip

  services:
    api-service:
      loadBalancer:
        passHostHeader: true
        servers:
          - url: "http://kolibri-api:8080"

    mq-dashboard-service:
      passHostHeader: true
      loadBalancer:
        servers:
          - url: "http://kolibri-broker:15672"

  middlewares:

    strip:
      stripPrefix:
        prefixes:
          - "/mq"

tcp:
  routers:
    broker-router:
      entryPoints:
        - "amqp"
      rule: "HostSNI(`*`)"
      service: broker-service
      tls:
        certResolver: acme_default
        domains:
          - main: <domain>

  services:
    broker-service:
      loadBalancer:
        servers:
          - address: "kolibri-broker:5678"
