http:
  routers:
    backend-router:
      entryPoints:
        - https
        - http
      rule: "PathPrefix(`/backend`)"
      service: backend-service
      tls:
        certResolver: acme_default
        domains:
          - main: <domain>
      middlewares:
        - strip

    mq-dashboard-router:
      entryPoints:
        - https
        - http
      rule: "PathPrefix(`/mq`)"
      service: mq-dashboard-service
      tls:
        certResolver: acme_default
        domains:
          - main: <domain>
      middlewares:
        - strip

    proxy-router:
      entryPoints:
        - https
        - http
      rule: "PathPrefix(`/api`) || PathPrefix(`/dashboard`)"
      service: api@internal
      tls:
        certResolver: acme_default
        domains:
          - main: <domain>
      middlewares:
        - auth

  services:
    backend-service:
      loadBalancer:
        passHostHeader: true
        servers:
          - url: "http://olivia-backend:8080"

    mq-dashboard-service:
      passHostHeader: true
      loadBalancer:
        servers:
          - url: "http://olivia-queue:15672"

  middlewares:
    auth:
      basicAuth:
        users:
          - "olivia:$2y$05$ngVIzd0/4.YMfe7pJEk5ye0jJXDYmr1AP4u2Hll28A.9kBP1yY3Q6" # Default user olivia

    strip:
      stripPrefix:
        prefixes:
          - "/backend"
          - "/mq"
